# Site settings
title:          pino.swift
description:    "Minimal Jekyll theme for storytellers"
baseurl:        ""
url:            "https://92pino.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Pino
  url:          https://92pino.github.io
  email:        jjb8382@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       100

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
